# Generated by Django 5.1.6 on 2025-03-11 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weathers', '0003_city_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='slug',
        ),
        migrations.CreateModel(
            name='CitySlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weathers.city')),
            ],
        ),
    ]
