# Generated by Django 5.1.6 on 2025-03-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weathers', '0005_alter_cityslug_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityslug',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
