# Generated by Django 5.1.6 on 2025-03-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weathers', '0006_alter_cityslug_slug'),
    ]

    operations = [
    ]
