# Generated by Django 5.1.6 on 2025-03-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weathers', '0007_auto_20250311_1939'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cityslug',
            table='city_slug_table',
        ),
    ]
