# Generated by Django 5.1.6 on 2025-03-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weathers', '0008_alter_cityslug_table'),
    ]

    operations = [
    ]
