# Generated by Django 5.1.6 on 2025-03-11 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weathers', '0009_auto_20250311_1949'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cityslug',
            table=None,
        ),
    ]
