# Generated by Django 5.1.6 on 2025-03-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weathers', '0012_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('emblem', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='administrative_division',
            field=models.CharField(default='Undefined', max_length=80),
        ),
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.DeleteModel(
            name='CitySlug',
        ),
    ]
