# Generated by Django 5.1.6 on 2025-03-13 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weathers', '0013_municipality_city_administrative_division_city_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='slug',
        ),
        migrations.CreateModel(
            name='CitySlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weathers.city')),
            ],
        ),
    ]
