# Generated by Django 5.1.6 on 2025-03-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weathers', '0014_remove_city_slug_cityslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityslug',
            name='slug',
            field=models.SlugField(),
        ),
    ]
